### ISSUE TITLE
Column indices are out of range

### ISSUE THREAD

**Issue by TommyDong1998** [mljs/random-forest#44]
The error "column indices are out of range error" appears when I try
regression.train([[73, 80],[93, 88]],[152,182])

Uncaught RangeError: column indices are out of range
    at checkColumnIndices (util.js:102:11)
    at new MatrixColumnSelectionView (columnSelection.js:7:21)
    at RandomForestRegression.train (RandomForestBase.js:130:20)
    at processRegression (index.html:74:28)
    at HTMLButtonElement.onclick (index.html:35:47)

**Comment by jepnoda** [comment]
Have you resolved this yet? I'm having the same problem.

**Comment by dorox1** [comment]
I know this very late as a reply to this issue, but I ran into the same issue and believe I have identified the cause.

The bagging/out-of-bag process in `examplesBaggingWithReplacement` fails non-deterministically (depending on the seed and dataset), with much higher probabilities for small datasets like yours. This makes toy and test examples unstable. It doesn't crash immediately, but it generates empty OOB sets which causes a crash later in the training process.

I'll submit a full bug report.
